services:
  server:
    build:
      context: .
    environment:
      - DISCORD_TOKEN_FILE=/run/secrets/discord-token
      - BOT_PREFIX=!
      - DATA_DIR=/data
    volumes:
      - ./data:/data
    secrets:
      - discord-token
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - ./data
secrets:
  discord-token:
    file: ./secrets/discord-token.txt
