services:
  server:
    build:
      context: .
    user: "10001:10001"
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - ./data
