services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/data
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - ./data

volumes:
  data:
